### ISSUE TITLE
Having Pi Issues..

### ISSUE THREAD

**Issue by sfitzjava** [joshmarinacci/aminogfx#11]
Hi Josh, 
  This is just the project I am needing to get working on my Pi.  
When I go through the setup instructions in the readme.md  it seems to do what is expected but when I try the "node demos/circle.js"  I get nothing on screen in the way of circles.  

Here is the environment information:
Node: v0.10.35
gcc: Debian 4.6.3-14+rpi1
linux: raspberrypi 3.12.26+ #7 PREEMPT wed sep 17 14:25:24 edt 2014 armv6l gnu/linux
Screen: PiTFT 2.8  (adafruit)  Framebuffer /dev/fb1   (https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/easy-install)   used their kernel.

(Anything else that would help to know?)

 Here is the console info after running the circle demo:

inside of the aminogfx main.js
sgtest =  { init: [Function],
  createWindow: [Function],
  setWindowSize: [Function],
  getWindowSize: [Function],
  createRect: [Function],
  createPoly: [Function],
  createGroup: [Function],
  createText: [Function],
  createGLNode: [Function],
  createAnim: [Function],
  stopAnim: [Function],
  updateProperty: [Function],
  updateAnimProperty: [Function],
  addNodeToGroup: [Function],
  removeNodeFromGroup: [Function],
  tick: [Function],
  selfDrive: [Function],
  setEventCallback: [Function],
  setRoot: [Function],
  decodePngBuffer: [Function],
  decodeJpegBuffer: [Function],
  loadBufferToTexture: [Function],
  createNativeFont: [Function],
  getCharWidth: [Function],
  getFontHeight: [Function],
  runTest: [Function],
  initColorShader: [Function],
  initTextureShader: [Function],
  GL_VERTEX_SHADER: 35633,
  GL_FRAGMENT_SHADER: 35632,
  GL_COMPILE_STATUS: 35713,
  GL_LINK_STATUS: 35714,
  glCreateShader: [Function],
  glShaderSource: [Function],
  glCompileShader: [Function],
  glGetShaderiv: [Function],
  glCreateProgram: [Function],
  glAttachShader: [Function],
  glUseProgram: [Function],
  glLinkProgram: [Function],
  glGetProgramiv: [Function],
  glGetAttribLocation: [Function],
  glGetUniformLocation: [Function],
  glGetProgramInfoLog: [Function] }
fully loaded
initing input for OS  RPI
doing native init. dpi scale = 1
RPI: display size = 720 x 480
rpi.c: got to the real opengl context
you are not root. this might not work
file = event2
initing a device
Reading from: /dev/input/event2 (stmpe-ts)
Location /dev/input/event2 (stmpe-ts/input0)
event type 0x00 sync events
event type 0x01 key events
event type 0x03 abs events
file = event1
initing a device
Reading from: /dev/input/event1 (  Mini Keyboard)
Location /dev/input/event1 (usb-bcm2708_usb-1.3/input1)
event type 0x00 sync events
event type 0x01 key events
event type 0x02 rel events
event type 0x03 abs events
event type 0x04 msc events
file = event0
initing a device
Reading from: /dev/input/event0 (  Mini Keyboard)
Location /dev/input/event0 (usb-bcm2708_usb-1.3/input0)
event type 0x00 sync events
event type 0x01 key events
event type 0x04 msc events
event type 0x11 led events
event type 0x14 rep events
WARNING. got -1 for location of  opacity
WARNING. got -1 for location of  tex
loading font file /home/pi/aminogfx-master/src/../resources/SourceSansPro-ExtraLight.ttf
loading font file /home/pi/aminogfx-master/src/../resources/SourceSansPro-Light.ttf
loading font file /home/pi/aminogfx-master/src/../resources/SourceSansPro-Regular.ttf
loading font file /home/pi/aminogfx-master/src/../resources/SourceSansPro-Semibold.ttf
loading font file /home/pi/aminogfx-master/src/../resources/SourceSansPro-Bold.ttf
loading font file /home/pi/aminogfx-master/src/../resources/SourceSansPro-Black.ttf
loading font file /home/pi/aminogfx-master/src/../resources/fontawesome-webfont.ttf
PureImage loading source undefined undefined undefined
starting the event loop

**Comment by joshmarinacci** [comment]
I don't think this will work. I think Adafruit's screen uses an in-memory framebuffer. This means it doesn't go through the GPU.  Amino only works with OpenGL, so I think you'll have to use a screen that attaches to the HDMI port. I'm sorry.

**Comment by dudewheresmycode** [comment]
If you haven't already. Checkout https://github.com/vesteraas/node-pitft. I had the reverse issue.
