### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by 4inn** [joshmarinacci/aminogfx#12]
Hello i need show with omxplayer one video on background of stage (layer -1) and upper this show a text or graphic... my problem is with transparent background of stage... is posible to get a example how set transparent background ? Very thanks

**Comment by joshmarinacci** [comment]
I'm sorry it's taken so long to reply. The whole family has been sick with a nasty cold that's been going around. 

Is this on the Raspberry Pi or other platform? There is no API to do this but I think we could add one. I think we just need to let you set the clear color that is used to clear the OpenGL window. It's currently hard coded to 1,0,0,1.

**Comment by 4inn** [comment]
Hello, thanks for your reply, and sorry with my english, is very bad!

I hope you family improve...

The hardware are Raspberry Pi

Is posible to add this option in you library ?

Or you help my for this modification ?

very thanks,
Michel

**Comment by joshmarinacci** [comment]
I'm in the middle of a bunch of refactoring work so I can add this.  What exactly is the thing you are looking for? Do you need to set the background color, opacity, or the layer? I think the standard layer is 0, so setting the clearcolor opacity to 0 I *think* would do the trick. Can you give me a simple program which reproduces the problem?  Then I can add an api like:

stage.opacity(0)

thanks.

**Comment by 4inn** [comment]
Hello, my intent is insert graphics over the video (the videoplayer is omxplayer).

Only i need the posibility to set the background of aminogfx to transparent to show the video in the background of graphics layer...

thank you very much again!

**Comment by joshmarinacci** [comment]
Implemented. Please see this blog for details on how to use it.

http://joshondesign.com/2015/02/27/aminorefactored

**Comment by movingbits** [comment]
Thanks, great!
