### ISSUE TITLE
Is this project still under development?

### ISSUE THREAD

**Issue by almilo** [joshmarinacci/aminogfx#13]
Hi Josh,
This project seems like a great idea to me and I was wondering if you are still working on it or it has been superseeded with something else?
Many thanks for the feedback and the cool work!!
Alberto

**Comment by joshmarinacci** [comment]
It's mainly in maintaining mode due to work stuff but it has not been superceded. I hope to get back to it later this month. Are there some features you need?

**Comment by almilo** [comment]
No, so far I was not able to install it yet :)
