### ISSUE TITLE
Issues install on Raspberry Pi 2 - Raspbian Jessie / Wheezy

### ISSUE THREAD

**Issue by patrickhampson** [joshmarinacci/aminogfx#16]
Hello,

When running npm install aminogfx-gl npm fails on fresh installs of raspbian jessie and wheezy.  
Attached is the npm-debug.txt any help is appreciated!

[npm-debug.txt](https://github.com/joshmarinacci/aminogfx/files/111093/npm-debug.txt)

**Comment by cbratschi** [comment]
I've had the same issue with the legacy node version. 4.x works fine:

curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -

**Comment by joshmarinacci** [comment]
Does this happen with Node v5?

**Comment by cbratschi** [comment]
I did not try v5 but the 0.x version was failing which Raspbian installs by default. I would guess 5.x works fine too.

**Comment by joshmarinacci** [comment]
Yes, that’s probably it. I’ve tried it with V4 and V5 and they work okay. I had to do some work a few months back to update to the newest version of NAN. I’m guessing 0.x isn’t supported anymore.
