### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by movingbits** [joshmarinacci/aminogfx#9]
I notice that memory use keeps growing till there is nothing left and the process is killed. (takes about 1 hour)
I observe this behaviour on my own tests and the demos

Fresh raspbian sept 2014, node 10.25, mem-split 256/256

**Comment by joshmarinacci** [comment]
Are you still having memory leak issues?

**Comment by movingbits** [comment]
I have not tested the refectored version. I hope to find the time next week.

**Comment by joshmarinacci** [comment]
no more reports so updating.
